id: I91977963
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:21:22+00:00'
last_modified: '2022-06-08T13:37:57.743603+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13769
  title: སྟག་ལུང་སྡོམ་གསུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    999D:
      image_group_id: I1KG15219
      title: ''
      total_pages: 462
      order: 1
      base_file: 999D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
