id: P010441
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:04.882115
source_metadata:
  id: bdr:W1KG13769
  title: སྟག་ལུང་སྡོམ་གསུམ།
  author: ''
  volumes:
    8dc4f50c276041e6a2857d9288fb0e1f:
      image_group_id: I1KG15219
      title: ''
      volume_number: 1
      total_pages: 462
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
